global using AirLine.Application.Common;
global using AirLine.Application.Interfaces.Repository;
global using AirLine.Domain.Common.Interface;
global using AirLine.Domain.Entities;
global using AirLine.Infrastructure.Persistence.AirLDbContext;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;